### ISSUE TITLE
Support multiple versions

### ISSUE THREAD

**Issue by Kristian-ZH** [gardener/docforge#223]
**What would you like to be added**:
Docforge should have a support for documentation with multiple versions.

/kind enhancement

**Subtask of this enhancement:**
- [x] 'LastNSupportedVersions' provided via default flag: `—-tags-token-map="defaultVersions=0,<repo-1>=3,<repo-2>=2 \`
   - [x] Main branch will be hardcoded to master
- [x] Use the handlers to fetch the default branch directly from the repo
   - [x] manifest file which is pointing to another manifest from another repo will have a placeholder for the branch field: 
      ```
      name: doc2FooIndex
      nodesSelector:
        path: https://github.com/foo/documentation/blob/defaultBranch/.docforge/documentationFoo.yaml
      ``` 
   - [x] 'LastNSupportedVersions' provided via default flag: `—-mainBranches-token-map="<repo-1>=main,<repo-2>=foo \`
   - [x] docforge should create a map[RepoPath]mainBranch which will contain the main branches for all repos supported in the manifest files:  If the repo's branch is provided via the `—-mainBranches-token-map` flag, then it will be taken from there. Otherwise, it will be taken from the `default` github branch of the repo.
   - [x] Use the created map to replace the `defaultBranch` variable in the manifest.
   - [x] Local setup should still be enough flexible: e.g. to test against different documentation branches.
- [ ] Create a config file used by docforge which will contain the configurations of the variables.
