### ISSUE TITLE
☂️-Issue for  dockforge refactoring

### ISSUE THREAD

**Issue by Kristian-ZH** [gardener/docforge#254]
**What would you like to be added**:
This issue includes:
- [x] Replace the custom maintained markdown parser with a standart one.
- [x] Stabilise the used handlers (Git and Github)
- [x] Cleanup the code from unsupported features and unwanted scenarios
- [x] Increase the code coverage with unit tests

**Why is this needed / describe a real-world scenario**:
Improve the tool quality. Support only the main scenarios and keep them working.

**How to categorize this?**:

/kind enhancement
/priority 3
